###############################################################################
# APP TIER – VM CREATION
###############################################################################
- name: App Tier - VM Creation
  hosts: localhost
  connection: local
  gather_facts: no

  vars:
    vm_flavor: "cmp"
    vm_image: "a997754d-6cdf-4a21-8e52-5df389d3f7c5"
    vm_keypair: "k8s"
    vm_net: "cb24a95d-378a-470b-9647-4849caca9fb2"

    os_auth_url: "http://192.168.170.50:5000"
    os_project_name: "Production Engineering"
    os_project_domain_id: "default"
    os_username: "admin"
    os_user_domain_name: "Default"
    os_password: "bLEZFvatBShkvUZyKrasUjmNdTTc9c3HcxWykrro"
    os_region_name: "RegionOne"
    os_interface: "public"

  tasks:
    - name: Verify App VM name
      debug:
        msg: "App VM name is {{ vm_name_app }}"

    - name: Create App VM
      openstack.cloud.server:
        auth:
          auth_url: "{{ os_auth_url }}"
          username: "{{ os_username }}"
          password: "{{ os_password }}"
          project_name: "{{ os_project_name }}"
          project_domain_id: "{{ os_project_domain_id }}"
          user_domain_name: "{{ os_user_domain_name }}"
        region_name: "{{ os_region_name }}"
        interface: "{{ os_interface }}"
        name: "{{ vm_name_app }}"
        image: "{{ vm_image }}"
        flavor: "{{ vm_flavor }}"
        key_name: "{{ vm_keypair }}"
        network: "{{ vm_net }}"
        wait: yes
        timeout: 600
      register: app_vm

    - name: Save App IP
      set_fact:
        app_ip: "{{ app_vm.server.public_v4 }}"

    - name: Add App VM to inventory
      add_host:
        name: "{{ app_vm.server.public_v4 }}"
        groups: app

###############################################################################
# APP TIER – APPLICATION SETUP
###############################################################################
- name: App Tier - Application Setup
  hosts: app
  become: yes
  gather_facts: yes

  vars:
    db_host: "{{ hostvars['localhost']['db_ip'] }}"
    db_name: appdb
    db_user: appuser
    db_password: "App@123"

  tasks:
    - name: Install required packages
      apt:
        name:
          - python3
          - python3-pip
        state: present
        update_cache: yes

    - name: Install PyMySQL
      pip:
        name: pymysql

    - name: Create app code
      copy:
        dest: /opt/app.py
        mode: '0755'
        content: |
          import pymysql
          from http.server import BaseHTTPRequestHandler, HTTPServer

          conn = pymysql.connect(
              host="{{ db_host }}",
              user="{{ db_user }}",
              password="{{ db_password }}",
              database="{{ db_name }}"
          )

          class Handler(BaseHTTPRequestHandler):
              def do_GET(self):
                  cur = conn.cursor()
                  cur.execute("SELECT name FROM users")
                  rows = cur.fetchall()
                  self.send_response(200)
                  self.send_header("Content-type", "text/html")
                  self.end_headers()
                  self.wfile.write(b"<h1>Users from MySQL</h1>")
                  for r in rows:
                      self.wfile.write(f"<p>{r[0]}</p>".encode())

          HTTPServer(("", 8080), Handler).serve_forever()

    - name: Start application
      shell: nohup python3 /opt/app.py &
