###############################################################################
# APP TIER – VM CREATION
###############################################################################
- name: App Tier - VM Creation
  hosts: localhost
  connection: local
  gather_facts: no

  vars:
    vm_image: a997754d-6cdf-4a21-8e52-5df389d3f7c5
    vm_flavor: cmp
    vm_net: cb24a95d-378a-470b-9647-4849caca9fb2
    vm_keypair: k1s

    os_auth_url: http://192.168.170.50:5000
    os_username: admin
    os_password: bLEZFvatBShkvUZyKrasUjmNdTTc9c3HcxWykrro
    os_project_name: "Production Engineering"
    os_project_domain_id: default
    os_user_domain_name: Default
    os_region_name: RegionOne
    os_interface: public

    cloud_init: |
      #cloud-config
      disable_root: false
      ssh_pwauth: true
      chpasswd:
        list: |
          root:Stackmax
        expire: false
      runcmd:
        - sed -i 's/^#\?PermitRootLogin .*/PermitRootLogin yes/' /etc/ssh/sshd_config
        - sed -i 's/^#\?PasswordAuthentication .*/PasswordAuthentication yes/' /etc/ssh/sshd_config
        - systemctl restart ssh || systemctl restart sshd

  tasks:
    - name: Create APP VM
      openstack.cloud.server:
        auth:
          auth_url: "{{ os_auth_url }}"
          username: "{{ os_username }}"
          password: "{{ os_password }}"
          project_name: "{{ os_project_name }}"
          project_domain_id: "{{ os_project_domain_id }}"
          user_domain_name: "{{ os_user_domain_name }}"
        region_name: "{{ os_region_name }}"
        interface: "{{ os_interface }}"
        name: "{{ vm_name_app }}"
        image: "{{ vm_image }}"
        flavor: "{{ vm_flavor }}"
        network: "{{ vm_net }}"
        key_name: "{{ vm_keypair }}"
        userdata: "{{ cloud_init }}"
        wait: yes
      register: app_vm

    - name: Extract APP IP
      set_fact:
        app_ip: >-
          {{ app_vm.server.addresses
             | dict2items
             | map(attribute='value')
             | first
             | selectattr('version', 'equalto', 4)
             | map(attribute='addr')
             | first }}

    - name: Expose APP IP to workflow
      set_stats:
        data:
          app_ip: "{{ app_ip }}"

    - name: Wait for SSH
      wait_for:
        host: "{{ app_ip }}"
        port: 22
        delay: 40
        timeout: 600

    - name: Add APP host
      add_host:
        name: "{{ app_ip }}"
        groups: app
        ansible_user: root
        ansible_password: Stackmax

###############################################################################
# APP TIER – APPLICATION SETUP
###############################################################################
- name: App Tier - App Setup
  hosts: app
  become: yes
  gather_facts: no

  vars:
    db_host: "{{ db_ip | default(db_ip_fallback | default(omit), true) }}"

  pre_tasks:
    - name: Validate DB IP availability
      fail:
        msg: >
          No DB IP provided.
          Run via Workflow (DB → APP) or provide db_ip_fallback in survey.
      when: db_host is not defined

  tasks:
    - name: Install dependencies
      apt:
        name:
          - python3
          - python3-pip
        state: present
        update_cache: yes

    - name: Install PyMySQL
      pip:
        name: pymysql

    - name: Deploy application
      copy:
        dest: /opt/app.py
        mode: '0755'
        content: |
          import pymysql
          from http.server import BaseHTTPRequestHandler, HTTPServer

          def get_users():
              conn = pymysql.connect(
                  host="{{ db_host }}",
                  user="appuser",
                  password="App@123",
                  database="appdb"
              )
              cur = conn.cursor()
              cur.execute("SELECT name FROM users")
              rows = cur.fetchall()
              conn.close()
              return rows

          class Handler(BaseHTTPRequestHandler):
              def do_GET(self):
                  users = get_users()
                  response = ""

                  for u in users:
                      response += f"{u[0]}<br>"

                  self.send_response(200)
                  self.send_header("Content-Type", "text/html")
                  self.send_header("Content-Length", str(len(response)))
                  self.end_headers()
                  self.wfile.write(response.encode())

          HTTPServer(("0.0.0.0", 8080), Handler).serve_forever()

    - name: Start application
      shell: |
        nohup python3 /opt/app.py > /var/log/app.log 2>&1 &
