###############################################################################
# APP TIER – VM CREATION + APPLICATION SETUP (FIXED)
###############################################################################
- name: App Tier - Provision & Configure
  hosts: localhost
  connection: local
  gather_facts: no

  vars:
    vm_name_app: app-vm
    vm_image: a997754d-6cdf-4a21-8e52-5df389d3f7c5
    vm_flavor: cmp
    vm_net: cb24a95d-378a-470b-9647-4849caca9fb2
    vm_keypair: k1s

    os_auth_url: http://192.168.170.50:5000
    os_username: admin
    os_password: bLEZFvatBShkvUZyKrasUjmNdTTc9c3HcxWykrro
    os_project_name: "Production Engineering"
    os_project_domain_id: default
    os_user_domain_name: Default
    os_region_name: RegionOne
    os_interface: public

    cloud_init: |
      #cloud-config
      disable_root: false
      ssh_pwauth: true
      chpasswd:
        list: |
          root:Stackmax
        expire: false
      runcmd:
        - sed -i 's/^#\?PermitRootLogin .*/PermitRootLogin yes/' /etc/ssh/sshd_config
        - sed -i 's/^#\?PasswordAuthentication .*/PasswordAuthentication yes/' /etc/ssh/sshd_config
        - systemctl restart ssh || systemctl restart sshd

  tasks:
    - name: Ensure DB IP is available
      fail:
        msg: "db_ip not received from DB job"
      when: db_ip is not defined

    - name: Create APP VM
      openstack.cloud.server:
        auth:
          auth_url: "{{ os_auth_url }}"
          username: "{{ os_username }}"
          password: "{{ os_password }}"
          project_name: "{{ os_project_name }}"
          project_domain_id: "{{ os_project_domain_id }}"
          user_domain_name: "{{ os_user_domain_name }}"
        region_name: "{{ os_region_name }}"
        interface: "{{ os_interface }}"
        name: "{{ vm_name_app }}"
        image: "{{ vm_image }}"
        flavor: "{{ vm_flavor }}"
        network: "{{ vm_net }}"
        key_name: "{{ vm_keypair }}"
        userdata: "{{ cloud_init }}"
        wait: yes
      register: app_vm

    - name: Extract APP IP
      set_fact:
        app_ip: "{{ app_vm.server.addresses | dict2items | map(attribute='value') | first | selectattr('version','equalto',4) | map(attribute='addr') | first }}"

    - set_stats:
        data:
          app_ip: "{{ app_ip }}"

    - wait_for:
        host: "{{ app_ip }}"
        port: 22
        delay: 40
        timeout: 600

    - add_host:
        name: "{{ app_ip }}"
        groups: app
        ansible_user: root
        ansible_password: Stackmax

###############################################################################
# APPLICATION SETUP
###############################################################################
- name: App Tier - Application Setup
  hosts: app
  become: yes
  gather_facts: no

  vars:
    db_host: "{{ db_ip }}"

  tasks:
    - name: Install dependencies
      apt:
        name:
          - python3
          - python3-pip
          - mysql-client
        state: present
        update_cache: yes

    - name: Install PyMySQL
      pip:
        name: pymysql

    - name: Wait for DB
      wait_for:
        host: "{{ db_host }}"
        port: 3306
        timeout: 120

    - name: Deploy interactive app (FIXED TEMPLATE)
      copy:
        dest: /opt/app.py
        mode: '0755'
        content: |
          import pymysql
          from http.server import BaseHTTPRequestHandler, HTTPServer
          from urllib.parse import parse_qs

          DB_HOST = "{{ db_host }}"
          DB_USER = "appuser"
          DB_PASS = "App@123"
          DB_NAME = "appdb"

          def conn():
              return pymysql.connect(
                  host=DB_HOST,
                  user=DB_USER,
                  password=DB_PASS,
                  database=DB_NAME
              )

          def get_users():
              c = conn()
              cur = c.cursor()
              cur.execute("SELECT name FROM users ORDER BY id DESC")
              rows = cur.fetchall()
              c.close()
              return rows

          def add_user(name):
              c = conn()
              cur = c.cursor()
              cur.execute("INSERT INTO users (name) VALUES (%s)", (name,))
              c.commit()
              c.close()

          HTML = """
          <html>
          <head>
            <title>3-Tier Demo</title>
            <style>
              body { font-family: Arial; background: #667eea; }
              .box { background: white; padding: 20px; width: 400px;
                     margin: 60px auto; border-radius: 10px; }
              h2 { text-align: center; }
              input { width: 70%; padding: 8px; }
              button { padding: 8px; background: #667eea; color: white; border: none; }
              .u { background: #f2f2f2; margin: 5px; padding: 8px; border-radius: 5px; }
            </style>
          </head>
          <body>
            <div class="box">
              <h2>🚀 3-Tier App</h2>
              <form method="POST">
                <input name="username" placeholder="Add user" required>
                <button>Add</button>
              </form>
              __USERS__
            </div>
          </body>
          </html>
          """

          class Handler(BaseHTTPRequestHandler):
              def do_GET(self):
                  users_html = ""
                  for u in get_users():
                      users_html += f"<div class='u'>👤 {u[0]}</div>"
                  page = HTML.replace("__USERS__", users_html)
                  data = page.encode()
                  self.send_response(200)
                  self.send_header("Content-Type", "text/html")
                  self.send_header("Content-Length", str(len(data)))
                  self.end_headers()
                  self.wfile.write(data)

              def do_POST(self):
                  length = int(self.headers.get("Content-Length", 0))
                  body = self.rfile.read(length).decode()
                  params = parse_qs(body)
                  if "username" in params:
                      add_user(params["username"][0])
                  self.send_response(303)
                  self.send_header("Location", "/")
                  self.end_headers()

          HTTPServer(("0.0.0.0", 8080), Handler).serve_forever()

    - name: Start app
      shell: nohup python3 /opt/app.py > /var/log/app.log 2>&1 &
