###############################################################################
# DB TIER – VM CREATION
###############################################################################
- name: DB Tier - VM Creation
  hosts: localhost
  connection: local
  gather_facts: no

  vars:
    # VM details
    vm_flavor: "2C_4R_150"
    vm_image: "a997754d-6cdf-4a21-8e52-5df389d3f7c5"
    vm_keypair: "k8s"
    vm_net: "cb24a95d-378a-470b-9647-4849caca9fb2"

    # OpenStack auth
    os_auth_url: "http://192.168.170.50:5000"
    os_project_name: "Production Engineering"
    os_project_domain_id: "default"
    os_username: "admin"
    os_user_domain_name: "Default"
    os_password: "bLEZFvatBShkvUZyKrasUjmNdTTc9c3HcxWykrro"
    os_region_name: "RegionOne"
    os_interface: "public"

  tasks:
    - name: Verify DB VM name from workflow survey
      debug:
        msg: "DB VM name is {{ vm_name_db }}"

    - name: Create DB VM (boot from image)
      openstack.cloud.server:
        auth:
          auth_url: "{{ os_auth_url }}"
          username: "{{ os_username }}"
          password: "{{ os_password }}"
          project_name: "{{ os_project_name }}"
          project_domain_id: "{{ os_project_domain_id }}"
          user_domain_name: "{{ os_user_domain_name }}"
        region_name: "{{ os_region_name }}"
        interface: "{{ os_interface }}"

        name: "{{ vm_name_db }}"
        image: "{{ vm_image }}"
        flavor: "{{ vm_flavor }}"
        key_name: "{{ vm_keypair }}"
        network: "{{ vm_net }}"
        security_groups:
          - default
        wait: yes
        timeout: 600
      register: db_vm

    - name: Extract DB private IP (generic & safe)
      set_fact:
        db_ip: >-
          {{
            db_vm.server.addresses
            | dict2items
            | map(attribute='value')
            | first
            | selectattr('version', 'equalto', 4)
            | map(attribute='addr')
            | first
          }}

    - name: Show DB private IP
      debug:
        msg: "DB private IP is {{ db_ip }}"

    - name: Wait for SSH to be available on DB VM
      wait_for:
        host: "{{ db_ip }}"
        port: 22
        delay: 20
        timeout: 300

    - name: Add DB VM to inventory
      add_host:
        name: "{{ db_ip }}"
        groups: db
        ansible_user: ubuntu

###############################################################################
# DB TIER – MYSQL CONFIGURATION
###############################################################################
- name: DB Tier - MySQL Setup
  hosts: db
  become: yes
  gather_facts: yes

  vars:
    db_name: appdb
    db_user: appuser
    db_password: "App@123"

  tasks:
    - name: Install MySQL Server
      apt:
        name: mysql-server
        state: present
        update_cache: yes

    - name: Allow MySQL remote connections
      lineinfile:
        path: /etc/mysql/mysql.conf.d/mysqld.cnf
        regexp: '^bind-address'
        line: 'bind-address = 0.0.0.0'
        backup: yes

    - name: Restart MySQL
      service:
        name: mysql
        state: restarted
        enabled: yes

    - name: Create application database
      shell: mysql --protocol=socket -e "CREATE DATABASE IF NOT EXISTS {{ db_name }};"

    - name: Create DB user and grant privileges
      shell: |
        mysql --protocol=socket -e "
        CREATE USER IF NOT EXISTS '{{ db_user }}'@'%' IDENTIFIED BY '{{ db_password }}';
        GRANT ALL PRIVILEGES ON {{ db_name }}.* TO '{{ db_user }}'@'%';
        FLUSH PRIVILEGES;
        "

    - name: Create users table
      shell: |
        mysql --protocol=socket {{ db_name }} -e "
        CREATE TABLE IF NOT EXISTS users (
          id INT AUTO_INCREMENT PRIMARY KEY,
          name VARCHAR(50)
        );
        "
