###############################################################################
# DB TIER – VM CREATION
###############################################################################
- name: DB Tier - VM Creation
  hosts: localhost
  connection: local
  gather_facts: no

  vars:
    vm_flavor: "2C_4R_150"
    vm_image: "a997754d-6cdf-4a21-8e52-5df389d3f7c5"
    vm_keypair: "k8s"
    vm_net: "cb24a95d-378a-470b-9647-4849caca9fb2"

    os_auth_url: "http://192.168.170.51:5000"
    os_project_name: "Production Engineering"
    os_project_domain_id: "default"
    os_username: "admin"
    os_user_domain_name: "Default"
    os_password: "bLEZFvatBShkvUZyKrasUjmNdTTc9c3HcxWykrro"
    os_region_name: "RegionOne"
    os_interface: "internal"

  tasks:
    - debug:
        msg: "Creating DB VM with name {{ vm_name_db }}"

    - name: Create DB VM (boot from volume)
      openstack.cloud.server:
        auth:
          auth_url: "{{ os_auth_url }}"
          username: "{{ os_username }}"
          password: "{{ os_password }}"
          project_name: "{{ os_project_name }}"
          project_domain_id: "{{ os_project_domain_id }}"
          user_domain_name: "{{ os_user_domain_name }}"
        region_name: "{{ os_region_name }}"
        interface: "{{ os_interface }}"
        name: "{{ vm_name_db }}"
        flavor: "{{ vm_flavor }}"
        image: "{{ vm_image }}"
        key_name: "{{ vm_keypair }}"
        network: "{{ vm_net }}"
        boot_from_volume: true
        volume_size: 50
        terminate_volume: true
        wait: yes
        timeout: 600
      register: db_vm

    - set_fact:
        db_ip: "{{ db_vm.server.public_v4 }}"

    - add_host:
        name: "{{ db_vm.server.public_v4 }}"
        groups: db

###############################################################################
# DB TIER – MYSQL CONFIGURATION
###############################################################################
- name: DB Tier - MySQL Setup
  hosts: db
  become: yes
  gather_facts: yes

  vars:
    db_name: appdb
    db_user: appuser
    db_password: "App@123"

  tasks:
    - apt:
        name: mysql-server
        state: present
        update_cache: yes

    - lineinfile:
        path: /etc/mysql/mysql.conf.d/mysqld.cnf
        regexp: '^bind-address'
        line: 'bind-address = 0.0.0.0'

    - service:
        name: mysql
        state: restarted
        enabled: yes

    - shell: mysql --protocol=socket -e "CREATE DATABASE IF NOT EXISTS {{ db_name }};"

    - shell: |
        mysql --protocol=socket -e "
        CREATE USER IF NOT EXISTS '{{ db_user }}'@'%' IDENTIFIED BY '{{ db_password }}';
        GRANT ALL PRIVILEGES ON {{ db_name }}.* TO '{{ db_user }}'@'%';
        FLUSH PRIVILEGES;
        "

    - shell: |
        mysql --protocol=socket {{ db_name }} -e "
        CREATE TABLE IF NOT EXISTS users (
          id INT AUTO_INCREMENT PRIMARY KEY,
          name VARCHAR(50)
        );
        "
