###############################################################################
# DB TIER – VM CREATION
###############################################################################
- name: DB Tier - VM Creation
  hosts: localhost
  connection: local
  gather_facts: no

  vars:
    vm_flavor: "2C_4R_150"
    vm_image: "a997754d-6cdf-4a21-8e52-5df389d3f7c5"
    vm_keypair: "k8s"
    vm_net: "cb24a95d-378a-470b-9647-4849caca9fb2"
    
    # New: Add your private key path
    ssh_private_key_path: "/path/to/your/k8s/private/key"  # UPDATE THIS PATH

    os_auth_url: "http://192.168.170.50:5000"
    os_project_name: "Production Engineering"
    os_project_domain_id: "default"
    os_username: "admin"
    os_user_domain_name: "Default"
    os_password: "bLEZFvatBShkvUZyKrasUjmNdTTc9c3HcxWykrro"
    os_region_name: "RegionOne"
    os_interface: "public"

    # ✅ FIXED cloud-init - Creates ubuntu user and injects SSH key
    cloud_init: |
      #cloud-config
      users:
        - name: ubuntu
          ssh-authorized-keys:
            - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC...  # ADD YOUR PUBLIC KEY HERE
          sudo: ['ALL=(ALL) NOPASSWD:ALL']
          groups: sudo
          shell: /bin/bash
      disable_root: true
      ssh_pwauth: false

  tasks:
    - name: Create DB VM
      openstack.cloud.server:
        auth:
          auth_url: "{{ os_auth_url }}"
          username: "{{ os_username }}"
          password: "{{ os_password }}"
          project_name: "{{ os_project_name }}"
          project_domain_id: "{{ os_project_domain_id }}"
          user_domain_name: "{{ os_user_domain_name }}"
        region_name: "{{ os_region_name }}"
        interface: "{{ os_interface }}"
        name: "{{ vm_name_db }}"
        image: "{{ vm_image }}"
        flavor: "{{ vm_flavor }}"
        key_name: "{{ vm_keypair }}"
        network: "{{ vm_net }}"
        userdata: "{{ cloud_init }}"
        security_groups: [default]
        wait: yes
      register: db_vm

    - name: Extract DB VM IP
      set_fact:
        db_ip: "{{ db_vm.server.addresses | dict2items | map(attribute='value') | first | selectattr('version','equalto',4) | map(attribute='addr') | first }}"

    - name: Wait for SSH to be available
      wait_for:
        host: "{{ db_ip }}"
        port: 22
        timeout: 300

    - name: Add DB host to inventory
      add_host:
        name: "{{ db_ip }}"
        groups: db
        ansible_user: ubuntu
        ansible_ssh_private_key_file: "{{ ssh_private_key_path }}"

###############################################################################
# DB TIER – MYSQL SETUP
###############################################################################
- name: DB Tier - MySQL Setup
  hosts: db
  become: yes
  gather_facts: yes

  tasks:
    - name: Update apt cache and install MySQL
      apt:
        name: mysql-server
        state: present
        update_cache: yes

    - name: Configure MySQL to listen on all interfaces
      lineinfile:
        path: /etc/mysql/mysql.conf.d/mysqld.cnf
        regexp: '^bind-address'
        line: 'bind-address = 0.0.0.0'

    - name: Restart and enable MySQL
      service:
        name: mysql
        state: restarted
        enabled: yes

    - name: Setup database, user, and table
      shell: |
        mysql -e "
        CREATE DATABASE IF NOT EXISTS appdb;
        CREATE USER IF NOT EXISTS 'appuser'@'%' IDENTIFIED BY 'App@123';
        GRANT ALL PRIVILEGES ON appdb.* TO 'appuser'@'%';
        FLUSH PRIVILEGES;
        CREATE TABLE IF NOT EXISTS appdb.users (
          id INT AUTO_INCREMENT PRIMARY KEY,
          name VARCHAR(50)
        );
        "
