- name: DB Tier
  hosts: localhost
  connection: local
  gather_facts: no

  vars:
    vm_name_db: "{{ vm_name_db }}"
    vm_image: a997754d-6cdf-4a21-8e52-5df389d3f7c5
    vm_flavor: 2C_4R_150
    vm_net: cb24a95d-378a-470b-9647-4849caca9fb2
    vm_keypair: k1s

    os_auth_url: http://192.168.170.50:5000
    os_username: admin
    os_password: bLEZFvatBShkvUZyKrasUjmNdTTc9c3HcxWykrro
    os_project_name: "Production Engineering"
    os_project_domain_id: default
    os_user_domain_name: Default
    os_region_name: RegionOne
    os_interface: public

    cloud_init: |
      #cloud-config
      users:
        - name: ansible
          sudo: ALL=(ALL) NOPASSWD:ALL
          shell: /bin/bash
          ssh_authorized_keys:
            - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCYTFyfBYWqV9TOFeKODgLfgFuCd8redSgZpRcMTPAtT57H4SlvI7oLzQKqDnzknrKh1hFL4YglwhXEdedvqAbhm5lE5z8HUj1bO1BsLJ1OtJSD/55olZe7yxJn4dE0GM AQ9+S5Mdp rcItVQ9RGAzj74rajUA/BtufOwra2XBUZbEA6G9qNuYqGLVl4KVmN7opaTWzeto v7h9dIaxE8fn7LoE5VPOE2kT/fU5l/bhIFnD/vYhVzXP Hxryrnkx2iUBH3vubsXdF3L2vqOFmV5fpOqXOPvEgeattkM0EXa5IliEmwauVuLH5/69KfPatXbKsnY+sC83+yvQiQHjxgCanCc

  tasks:
    - name: Create DB VM
      openstack.cloud.server:
        auth:
          auth_url: "{{ os_auth_url }}"
          username: "{{ os_username }}"
          password: "{{ os_password }}"
          project_name: "{{ os_project_name }}"
          project_domain_id: "{{ os_project_domain_id }}"
          user_domain_name: "{{ os_user_domain_name }}"
        region_name: "{{ os_region_name }}"
        interface: "{{ os_interface }}"
        name: "{{ vm_name_db }}"
        image: "{{ vm_image }}"
        flavor: "{{ vm_flavor }}"
        network: "{{ vm_net }}"
        key_name: "{{ vm_keypair }}"
        userdata: "{{ cloud_init }}"
        wait: yes
      register: db_vm

    - set_fact:
        db_ip: "{{ db_vm.server.addresses | dict2items | map(attribute='value') | first | selectattr('version','equalto',4) | map(attribute='addr') | first }}"

    - add_host:
        name: "{{ db_ip }}"
        groups: db
        ansible_user: ansible

- name: Configure MySQL
  hosts: db
  become: yes

  tasks:
    - apt:
        name: mysql-server
        state: present
        update_cache: yes

    - shell: |
        mysql -e "
        CREATE DATABASE IF NOT EXISTS appdb;
        CREATE USER IF NOT EXISTS 'appuser'@'%' IDENTIFIED BY 'App@123';
        GRANT ALL PRIVILEGES ON appdb.* TO 'appuser'@'%';
        FLUSH PRIVILEGES;
        CREATE TABLE IF NOT EXISTS appdb.users (id INT AUTO_INCREMENT PRIMARY KEY, name VARCHAR(50));
        "
