###############################################################################
# WEB TIER – VM CREATION (IMAGE ONLY, NO VOLUME)
###############################################################################
- name: Web Tier - VM Creation
  hosts: localhost
  connection: local
  gather_facts: no

  vars:
    vm_image: a997754d-6cdf-4a21-8e52-5df389d3f7c5
    vm_flavor: cmp
    vm_net: cb24a95d-378a-470b-9647-4849caca9fb2
    vm_keypair: k1s

    os_auth_url: http://192.168.170.50:5000
    os_username: admin
    os_password: bLEZFvatBShkvUZyKrasUjmNdTTc9c3HcxWykrro
    os_project_name: "Production Engineering"
    os_project_domain_id: default
    os_user_domain_name: Default
    os_region_name: RegionOne
    os_interface: public

    cloud_init: |
      #cloud-config
      disable_root: false
      ssh_pwauth: true
      chpasswd:
        list: |
          root:Stackmax
        expire: false
      runcmd:
        - sed -i 's/^#\?PermitRootLogin .*/PermitRootLogin yes/' /etc/ssh/sshd_config
        - sed -i 's/^#\?PasswordAuthentication .*/PasswordAuthentication yes/' /etc/ssh/sshd_config
        - systemctl restart ssh || systemctl restart sshd

  tasks:
    - name: Create WEB VM (boot from image only)
      openstack.cloud.server:
        state: present                # ✅ important
        auth:
          auth_url: "{{ os_auth_url }}"
          username: "{{ os_username }}"
          password: "{{ os_password }}"
          project_name: "{{ os_project_name }}"
          project_domain_id: "{{ os_project_domain_id }}"
          user_domain_name: "{{ os_user_domain_name }}"
        region_name: "{{ os_region_name }}"
        interface: "{{ os_interface }}"
        name: "{{ vm_name_web }}"
        image: "{{ vm_image }}"        # ✅ image boot
        flavor: "{{ vm_flavor }}"
        network: "{{ vm_net }}"
        key_name: "{{ vm_keypair }}"
        userdata: "{{ cloud_init }}"
        wait: yes
        timeout: 600
      register: web_vm

    - name: Extract WEB IP
      set_fact:
        web_ip: >-
          {{
            web_vm.server.addresses
            | dict2items
            | map(attribute='value')
            | first
            | selectattr('version','equalto',4)
            | map(attribute='addr')
            | first
          }}

    - name: Wait for SSH on WEB VM
      wait_for:
        host: "{{ web_ip }}"
        port: 22
        delay: 40
        timeout: 600

    - name: Add WEB host
      add_host:
        name: "{{ web_ip }}"
        groups: web
        ansible_user: root
        ansible_password: Stackmax

###############################################################################
# WEB TIER – NGINX (PROXY TO APP TIER)
###############################################################################
- name: Web Tier - Nginx Setup
  hosts: web
  become: yes
  gather_facts: yes

  vars:
    app_backend_ip: "{{ app_ip }}"

  pre_tasks:
    - name: Validate APP IP from workflow
      fail:
        msg: >
          app_ip is not defined.
          Run this job ONLY via Workflow (DB → APP → WEB).
      when: app_backend_ip is not defined

  tasks:
    - name: Install nginx
      apt:
        name: nginx
        state: present
        update_cache: yes

    - name: Configure nginx reverse proxy
      copy:
        dest: /etc/nginx/sites-available/default
        content: |
          server {
            listen 80;
            location / {
              proxy_pass http://{{ app_backend_ip }}:8080;
              proxy_set_header Host $host;
              proxy_set_header X-Real-IP $remote_addr;
            }
          }

    - name: Restart nginx
      service:
        name: nginx
        state: restarted
        enabled: yes
