###############################################################################
# WEB TIER – VM CREATION
###############################################################################
- name: Web Tier - VM Creation
  hosts: localhost
  connection: local
  gather_facts: no

  vars:
    vm_flavor: "cmp"
    vm_image: "a997754d-6cdf-4a21-8e52-5df389d3f7c5"
    vm_keypair: "k8s"
    vm_net: "cb24a95d-378a-470b-9647-4849caca9fb2"

    os_auth_url: "http://192.168.170.50:5000"
    os_project_name: "Production Engineering"
    os_project_domain_id: "default"
    os_username: "admin"
    os_user_domain_name: "Default"
    os_password: "bLEZFvatBShkvUZyKrasUjmNdTTc9c3HcxWykrro"
    os_region_name: "RegionOne"
    os_interface: "public"

  tasks:
    - name: Verify Web VM name
      debug:
        msg: "Web VM name is {{ vm_name_web }}"

    - name: Create Web VM
      openstack.cloud.server:
        auth:
          auth_url: "{{ os_auth_url }}"
          username: "{{ os_username }}"
          password: "{{ os_password }}"
          project_name: "{{ os_project_name }}"
          project_domain_id: "{{ os_project_domain_id }}"
          user_domain_name: "{{ os_user_domain_name }}"
        region_name: "{{ os_region_name }}"
        interface: "{{ os_interface }}"
        name: "{{ vm_name_web }}"
        image: "{{ vm_image }}"
        flavor: "{{ vm_flavor }}"
        key_name: "{{ vm_keypair }}"
        network: "{{ vm_net }}"
        wait: yes
        timeout: 600
      register: web_vm

    - name: Add Web VM to inventory
      add_host:
        name: "{{ web_vm.server.public_v4 }}"
        groups: web

###############################################################################
# WEB TIER – NGINX REVERSE PROXY
###############################################################################
- name: Web Tier - Nginx Setup
  hosts: web
  become: yes
  gather_facts: yes

  vars:
    app_ip: "{{ hostvars['localhost']['app_ip'] }}"

  tasks:
    - name: Install Nginx
      apt:
        name: nginx
        state: present
        update_cache: yes

    - name: Configure Nginx reverse proxy
      copy:
        dest: /etc/nginx/sites-available/default
        content: |
          server {
              listen 80;
              location / {
                  proxy_pass http://{{ app_ip }}:8080;
              }
          }

    - name: Restart Nginx
      service:
        name: nginx
        state: restarted
        enabled: yes
